Asus: Remove System.Management
DarthAffe/RGB.NET pull request #335
Opened 2023-06-14 20:45 UTC by Aytackydln

I've had dependency problem with Aurora and my only solution was this. I know this is project specific change but I think this dependency is unnecessary anyway.

It should be removed so that it won't be problem for other projects in the future.

2023-06-14 22:19 UTC, DarthAffe commented
what is the issue with the dependency?
since this is quite a major breaking change for the provider i'd prefer to fix the actual problem.

2023-06-15 21:20 UTC, Aytackydln commented
Error was like "Interop.AuraServiceLib.dll not found" or something. Research on internet said it was version conflict. I used various tools to figure out the conflict but none of them gave any clue. Difference between Aurora and Artemis was .net version and System.* dependencies. Removing System.Management from this library fixed my problem

2023-06-15 21:25 UTC, DarthAffe commented
This doesn't make any sense - if the error is "Interop.AuraServiceLib.dll not found" then it normally is exactly this - sometimes aura does not correctly register it in the GAC, that's why artemis is distributing it.

2023-06-15 21:26 UTC, Aytackydln commented
I made sure to put the dll everywhere it can be found...

2023-06-15 21:32 UTC, DarthAffe commented
yeah, but this change is also breaking device detection for some devices and i really can't see any relation between that dependency and the capability of finding a library.
can you provide a full error message and stacktrace for the error?

2023-06-15 21:41 UTC, DarthAffe commented
from looking at it i'd say you have your version conflict in aurora as you're explicitely referencing 6.0.0 of System.Management, the provider uses 7.0.0.
i still don't see why that would cause in issue related to the interop lib but you'd need to generate binding redirects to fix that (or update the lib in aurora)

2023-06-18 15:03 UTC, Aytackydln commented
Well I'm out of arguments :)

2024-06-19 21:17 UTC, MesrineNathanael commented
Thank you for your fix, it fixed the issue with the asus aura devices for me too, I was having the same issue as you had :)

2024-10-20 09:22 UTC, DarthAffe requested changes

2024-10-20 09:22 UTC, DarthAffe commented on RGB.NET.Devices.Asus/Keyboard/AsusKeyboardRGBDeviceInfo.cs
> +    private static string? GetKeyboardModel(string deviceName) => GENERIC_DEVICE_NAMES.Contains(deviceName) ? "Asus Motherboard" : deviceName;
```suggestion
    private static string? GetKeyboardModel(string deviceName) => GENERIC_DEVICE_NAMES.Contains(deviceName) ? "Asus Keyboard" : deviceName;
```

2024-10-20 09:23 UTC, DarthAffe approved these changes

2024-10-20 09:26 UTC, merged